[project]
name = "experimentations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AlexR", email = "alex.richaume1@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "torch>=2.14.0",
    "torchvision>=0.29.0",
]

[project.scripts]
experimentations = "experimentations:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu130", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
